[package]
name = "hun_law"
version = "0.1.0"
edition = "2021"

authors = ["Alex Badics <admin@stickman.hu>"]
license = "GPL-3.0-only"


[dependencies]
anyhow = "1.0"
fn-error-context = "0.2"
serde = "1.0"
serde_json = "1.0"
flate2 = "1.0"
