[package]
name = "hun_law"
version = "0.1.0"
edition = "2021"

authors = ["Alex Badics <admin@stickman.hu>"]
license = "GPL-3.0-only"


[dependencies]
anyhow = "1.0"
fn-error-context = "0.2"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
flate2 = "1.0"
clap = {version = "3.1", features = ["derive"]}
ureq = "2.4"
log = "0.4.14"
env_logger = "0.9.0"

[dev-dependencies]
rstest = "0.12"
tempfile = "3"
